name: Jupyter
on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
# Шаги представляют собой последовательность задач, которые будут выполняться как часть задания
    steps:
      - name: Checkout # Извлечение репозитория в $GITHUB_WORKSPACE, чтобы задание могло получить к нему доступ
        uses: actions/checkout@v3
      - name: Setup Python # Установка python окружения для выполнения задания
        uses: actions/setup-python@v4.0.0
        with:
          cache: pip
          python-version: '3.7'
      - name: Install Dependencies # Установка зависимостей для Jupyter
        run: pip install nbconvert
      - name: Exeute Notebook # Выполнение тетрадки Jupyter
        run: jupyter-nbconvert --execute Parse Image.ipynb --to html
      - name: Upload a Build Artifact # Выгрузка вывода тетрадки (артефакта задания) в html файл
        uses: actions/upload-artifact@v3.1.0
        with:
          name: Artifact
          path: Parse Image.html
